# Generated by Django 4.2.23 on 2025-09-13 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditeeOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('auditor_name', models.CharField(max_length=255)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_year', models.IntegerField()),
                ('planed_quarter', models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2, null=True)),
                ('plan_status', models.CharField(choices=[('Planned', 'Planned'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Overdue', 'Overdue')], max_length=20)),
                ('assigned_team', models.CharField(blank=True, max_length=255, null=True)),
                ('current_year', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AuditType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('achieved_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashbords.auditor')),
            ],
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_task_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Overdue', 'Overdue')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('progress_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashbords.objective')),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding', models.TextField()),
                ('criticality_level', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('audit_team', models.CharField(blank=True, max_length=255, null=True)),
                ('auditee_organization', models.CharField(blank=True, max_length=255, null=True)),
                ('overdue_status', models.BooleanField(default=False)),
                ('rectification_status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('rectification_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('assigned_team', models.CharField(blank=True, max_length=255, null=True)),
                ('rectification_description', models.TextField(blank=True, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('auditor_comments', models.TextField(blank=True, null=True)),
                ('follower_id', models.IntegerField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashbords.auditplan')),
            ],
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2)),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('On-Track', 'On-Track'), ('Overdue', 'Overdue'), ('Completed', 'Completed')], max_length=20)),
                ('status_details', models.TextField(blank=True, null=True)),
                ('phase', models.CharField(choices=[('Pre-Engagement', 'Pre-Engagement'), ('Fieldwork', 'Fieldwork'), ('Reporting', 'Reporting'), ('Followup', 'Followup')], max_length=20)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashbords.auditplan')),
            ],
        ),
        migrations.AddField(
            model_name='auditplan',
            name='audit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashbords.audittype'),
        ),
        migrations.AddField(
            model_name='auditplan',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashbords.auditobject'),
        ),
        migrations.AddField(
            model_name='auditor',
            name='expertise_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashbords.audittype'),
        ),
        migrations.AddField(
            model_name='auditobject',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashbords.audittype'),
        ),
        migrations.AlterUniqueTogether(
            name='auditplan',
            unique_together={('object', 'plan_year')},
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performer_id', models.IntegerField()),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashbords.engagement')),
                ('responsibility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashbords.responsibility')),
            ],
            options={
                'unique_together': {('performer_id', 'engagement', 'responsibility')},
            },
        ),
    ]
